name: Bug
description: Report a bug or problem
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Describe the problem you're experiencing and how to reproduce it.
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Describe what you did...
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
  - type: input
    id: actual
    attributes:
      label: Actual Behavior
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
