name: Enhancement
description: Improve or extend an existing feature
labels: ["type: enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement
        Describe how an existing feature can be improved.
  - type: input
    id: feature
    attributes:
      label: What feature is being enhanced?
  - type: textarea
    id: improvement
    attributes:
      label: What is the suggested improvement?
  - type: textarea
    id: reason
    attributes:
      label: Why is this improvement needed?
